version: "3"
services:
  lannexxerajenkins:
    build: ./jenkins
    networks:
      - subnet-lab
  lannexxerajava:
    build: ./java
    networks:
      - subnet-lab
  lannexxeraftp:
    build: ./ftp
    networks:
      - subnet-lab
networks:
  subnet-lab:
      external: true

